import json

import spotipy
from spotipy.oauth2 import SpotifyOAuth

from mapa.config import PLAYLIST_PREFIX, SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REDIRECT_URI
from mapa.models import Song

SCOPES = "user-library-read playlist-modify-private playlist-modify-public"


def get_client() -> spotipy.Spotify:
    auth_manager = SpotifyOAuth(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET,
        redirect_uri=SPOTIFY_REDIRECT_URI,
        scope=SCOPES,
    )
    return spotipy.Spotify(auth_manager=auth_manager)


def fetch_liked_songs(sp: spotipy.Spotify) -> list[Song]:
    """Fetch all liked songs with pagination. Returns songs with artist IDs stored in genres field temporarily."""
    songs: list[Song] = []
    # Track artist IDs per song for genre enrichment
    song_artist_ids: dict[str, list[str]] = {}
    offset = 0

    while True:
        results = sp.current_user_saved_tracks(limit=50, offset=offset)
        items = results.get("items", [])
        if not items:
            break

        for item in items:
            track = item["track"]
            artist_names = ", ".join(a["name"] for a in track["artists"])
            artist_ids = [a["id"] for a in track["artists"] if a.get("id")]
            song_id = track["id"]

            songs.append(
                Song(
                    spotify_id=song_id,
                    name=track["name"],
                    artist=artist_names,
                    album=track["album"]["name"],
                    added_at=item.get("added_at"),
                )
            )
            song_artist_ids[song_id] = artist_ids

        offset += len(items)
        if not results.get("next"):
            break

    return _enrich_with_genres(sp, songs, song_artist_ids)


def _enrich_with_genres(
    sp: spotipy.Spotify,
    songs: list[Song],
    song_artist_ids: dict[str, list[str]],
) -> list[Song]:
    """Fetch artist genres in batches and attach them to songs."""
    # Collect all unique artist IDs
    all_artist_ids = list({
        aid
        for ids in song_artist_ids.values()
        for aid in ids
    })

    # Fetch genres in batches of 50 (Spotify API limit)
    artist_genres: dict[str, list[str]] = {}
    for i in range(0, len(all_artist_ids), 50):
        batch = all_artist_ids[i : i + 50]
        try:
            results = sp.artists(batch)
            for artist in results.get("artists", []):
                if artist:
                    artist_genres[artist["id"]] = artist.get("genres", [])
        except Exception:
            pass

    # Attach genres to songs
    enriched = []
    for song in songs:
        genres: set[str] = set()
        for aid in song_artist_ids.get(song.spotify_id, []):
            genres.update(artist_genres.get(aid, []))
        genre_json = json.dumps(sorted(genres)) if genres else None
        enriched.append(song.model_copy(update={"genres": genre_json}))

    return enriched


def create_playlist(
    sp: spotipy.Spotify, category_name: str, song_ids: list[str]
) -> str:
    """Create a Spotify playlist and add songs. Returns the playlist ID."""
    user_id = sp.current_user()["id"]
    playlist_name = f"{PLAYLIST_PREFIX} {category_name}"

    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_name,
        public=False,
        description=f"Auto-generated by mapa",
    )
    playlist_id = playlist["id"]

    _add_tracks_to_playlist(sp, playlist_id, song_ids)
    return playlist_id


def add_to_existing_playlist(
    sp: spotipy.Spotify, playlist_id: str, song_ids: list[str]
) -> None:
    """Add songs to an existing playlist."""
    _add_tracks_to_playlist(sp, playlist_id, song_ids)


def _add_tracks_to_playlist(
    sp: spotipy.Spotify, playlist_id: str, song_ids: list[str]
) -> None:
    """Add tracks in batches of 100 (Spotify API limit)."""
    uris = [f"spotify:track:{sid}" for sid in song_ids]
    for i in range(0, len(uris), 100):
        sp.playlist_add_items(playlist_id, uris[i : i + 100])
